In [7]:
from officelib.xllib import *
xl = Excel()
wb = xl.RecentFiles(3).Open()
ws = wb.Worksheets(1)
cells = ws.Cells
cr = cells.Range

In [19]:
from officelib.const import xlconst as xlc

In [6]:
c1 = cr("Q5")
mgc = cr("Q4")
o2c = cr("P5")
c2 = cr("P19")

def xlr(i):
    return range(1, i+1)

for c in xlr(5):
    for r in xlr(5):
        cv = c1.Offset(r,c)
        mg = mgc.Offset(1,c).Value
        o2 = o2c.Offset(r,1).Value
        cr(c2, c2.Offset(1,3)).Value = [(mg, o2, cv.Value)]
        c2 =c2.Offset(2,1)

In [33]:
import contextlib

@contextlib.contextmanager
def highlight(*cells):
    for c in cells:
        c.Interior.Color = 65535
        c.Interior.Pattern = xlc.xlSolid
    try:
        yield
    finally:
        for c in cells:
            c.Interior.Pattern = xlc.xlNone

In [34]:
from time import sleep
# Matrix multiplication
m1r, m1c = (5,6)
m2r, m2c = (6,5)
m1a = "Z13"
m2a = "AG13"
m3a = "Z22"

def cd(j):
    c1 = cr(m2a).Offset(1,j)
    return cr(c1, c1.Offset(m2r))

for r in xlr(m1r):
    m1cl = cr(m1a).Offset(r,1)
    m1rv = cr(m1cl, m1cl.Offset(1, m1c))
    for c in xlr(m2c):
        m2cv = cd(c)
        assert len(list(m1rv)) == len(list(m2cv)), (m1rv.Address, m2rv.Address)
        
        parts = []
        dstc = cr(m3a).Offset(r,c)
        with highlight(dstc):
            for a,b in zip(m1rv, m2cv):
                with highlight(a,b):
                    parts.append("%s*%s"%(a.Address, b.Address))
                    sleep(0.1)
            dstc.Value = "=" + "+".join(parts)
        
    
    

In [35]:
import numpy as np

In [36]:
np.matrix?

In [37]:
m = np.matrix(xl.Selection.Value)

In [53]:
p = m*m.T

In [56]:
np.linalg.inv(p)

matrix([[  302.71236708,  -253.09000933,  -396.41927531,   288.52017766,
            60.45445471],
        [ -253.09000933,   644.78329957,  -451.68794959,   -12.54094692,
            72.22754699],
        [ -396.41927531,  -451.68794959,  2597.97748897, -2069.77132221,
           322.07360235],
        [  288.52017766,   -12.54094692, -2069.77132221,  2905.60954914,
         -1118.14570061],
        [   60.45445471,    72.22754699,   322.07360235, -1118.14570061,
           666.57174431]])

In [57]:
_m = np.matrix(xl.Selection.Value)
np.linalg.inv(_m*_m.T)

matrix([[  265.15437713,  -248.37203191,  -331.80224108,   281.56311561,
            31.97822366],
        [ -248.37203191,   644.19063444,  -459.80504289,   -11.66701139,
            75.80468771],
        [ -331.80224108,  -459.80504289,  2486.80644075, -2057.80197248,
           371.06583006],
        [  281.56311561,   -11.66701139, -2057.80197249,  2904.32085631,
         -1123.42050117],
        [   31.97822366,    75.80468771,   371.06583006, -1123.42050117,
           644.98124557]])

In [112]:
x = np.array(xl.Selection.Value).T

In [108]:
y = np.array([v[0] for v in xl.Selection.Value])

In [113]:
n = x.shape[0]
X = np.vstack(list(itertools.chain([np.ones(30)], x))).T
np.linalg.lstsq(X, y)[0]

array([  4.00000000e-01,   2.00000000e-01,   9.80000000e-01,
        -3.77570476e-17])

In [76]:
IdentityMatrix = np.zeros((30,30))
np.fill_diagonal(IdentityMatrix, 1)

In [83]:
lamb = 1
X = x
xtdx = X.T.dot(X)
xtdy = X.T.dot(y)
th = np.linalg.lstsq(xtdx + lamb * IdentityMatrix, xtdy)[0]  

ValueError: operands could not be broadcast together with shapes (3,3) (30,30) 

In [ ]:

IdentityMatrix = np.zeros((30,30))
np.fill_diagonal(IdentityMatrix, 1)
lamb = 1

xTx = X.T.dot(X) + lamb * IdentityMatrix
XtX = np.linalg.inv(xTx)
XtX_xT = XtX.dot(X.T)
theta = XtX_xT.dot(y)